default:
  image: gradle:jdk11

build:
  stage: compilation
  script:
    - cd TourGuide/
    - ./gradlew clean
    - ./gradlew classes
    - ./gradlew testClasses

test:
  stage: tests
  script:
    - cd TourGuide/
    - ./gradlew test
    - cat build/jacocoHtml/index.html | grep -o '<tfoot>.*</tfoot>'
  coverage: '/Total.*?([0-9]{1,3})%/'
  
  artifacts:
    when: always
    paths:
      - TourGuide/build/jacocoHtml
      - TourGuide/build/reports
      - TourGuide/build/jacoco/test.exec
    reports:
      junit: TourGuide/build/test-results/test/TEST-*.xml  
