run_test:
  image: gradle:jdk11
  script:
    - cd TourGuide/
    - ./gradlew test
  artifacts:
    when: always
    paths:
      - jacocoTestReport.xml
    reports:
      junit: build/jacocoTestReport.xml   
